### ISSUE TITLE
Reg File Parser Error 

### ISSUE THREAD

**Issue by Nitika1992** [alb1183/ML-RL-PureEdgeSim#3]
Dear Sir
I'm really enlighted by your work on Edge computing paradigm and found it quite interesting. It would be a great help if you can assist with fixing this error.
Thanks in Anticipation.

Main- Loading simulation files...
FilesParser- Checking simulation properties file
java.io.FileNotFoundException: PureEdgeSim/settings/simulation_parameters.properties (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:212)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:154)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:109)
	at com.pureedgesim.scenariomanager.FilesParser.checkSimulationProperties(FilesParser.java:57)
	at com.pureedgesim.scenariomanager.FilesParser.checkFiles(FilesParser.java:47)
	at com.pureedgesim.simulationcore.Simulation.launchSimulation(Simulation.java:62)
	at com.pureedgesim.MainApplication.main(MainApplication.java:10)
FilesParser- Failed to load properties file!

**Comment by alb1183** [comment]
The problem is in the third lione, the simulator can't find the simulation parameters file:
java.io.FileNotFoundException: PureEdgeSim/settings/simulation_parameters.properties (No such file or directory)

Please check if you have the files in the right folder.
Those files are in the repository (ML-RL-PureEdgeSim/PureEdgeSim/pruebas/settings/)

**Comment by Nitika1992** [comment]
It's not helping out. It shows there are errors in project while Running. 
Although the required file is already there in settings folder. 
The code is not working after
FilesParser fp = new FilesParser();   in simulation File
Kindly help!

**Comment by Nitika1992** [comment]
Can you help me out with this Error?
Simulation progress : [ 0 java.lang.ClassCastException: class com.pureedgesim.tasksorchestration.DefaultOrchestrator cannot be cast to class pruebas.CustomEdgeOrchestrator (com.pureedgesim.tasksorchestration.DefaultOrchestrator and pruebas.CustomEdgeOrchestrator are in unnamed module of loader 'app')
Main- The simulation has been terminated due to an unexpected error

Thanks in Antipication!

**Comment by thinkOver87** [comment]
I am working on this domain and wants to check the applicability. I face this problem

imulation progress : [ 0 java.lang.ClassCastException: class com.pureedgesim.tasksorchestration.DefaultOrchestrator cannot be cast to class pruebas.CustomEdgeOrchestrator (com.pureedgesim.tasksorchestration.DefaultOrchestrator and pruebas.CustomEdgeOrchestrator are in unnamed module of loader 'app')
	at com.pureedgesim.simulationvisualizer.MultiRLChart.update(MultiRLChart.java:48)
	at com.pureedgesim.simulationvisualizer.SimulationVisualizer.lambda$1(SimulationVisualizer.java:109)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.pureedgesim.simulationvisualizer.SimulationVisualizer.repaint(SimulationVisualizer.java:109)
	at com.pureedgesim.simulationvisualizer.SimulationVisualizer.updateCharts(SimulationVisualizer.java:98)
	at com.pureedgesim.simulationcore.SimulationManager.processEvent(SimulationManager.java:156)
	at org.cloudbus.cloudsim.core.CloudSimEntity.run(CloudSimEntity.java:344)
	at org.cloudbus.cloudsim.core.CloudSim.executeRunnableEntities(CloudSim.java:575)
	at org.cloudbus.cloudsim.core.CloudSim.runClockTickAndProcessFutureEvents(CloudSim.java:498)
	at org.cloudbus.cloudsim.core.CloudSim.processEvents(CloudSim.java:299)
	at org.cloudbus.cloudsim.core.CloudSim.start(CloudSim.java:258)
	at com.pureedgesim.simulationcore.SimulationManager.startSimulation(SimulationManager.java:66)
	at com.pureedgesim.simulationcore.SimulationThread.startSimulation(SimulationThread.java:97)
	at com.pureedgesim.simulationcore.Simulation.launchSimulation(Simulation.java:79)
	at com.pureedgesim.MainApplication.main(MainApplication.java:10)
