### ISSUE TITLE
Class not cast problem

### ISSUE THREAD

**Issue by thinkOver87** [alb1183/ML-RL-PureEdgeSim#5]
Simulation progress : [ 0 java.lang.ClassCastException: class com.pureedgesim.tasksorchestration.DefaultOrchestrator cannot be cast to class pruebas.CustomEdgeOrchestrator (com.pureedgesim.tasksorchestration.DefaultOrchestrator and pruebas.CustomEdgeOrchestrator are in unnamed module of loader 'app')
	at com.pureedgesim.simulationvisualizer.MultiRLChart.update(MultiRLChart.java:48)
	at com.pureedgesim.simulationvisualizer.SimulationVisualizer.lambda$1(SimulationVisualizer.java:109)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.pureedgesim.simulationvisualizer.SimulationVisualizer.repaint(SimulationVisualizer.java:109)
	at com.pureedgesim.simulationvisualizer.SimulationVisualizer.updateCharts(SimulationVisualizer.java:98)
	at com.pureedgesim.simulationcore.SimulationManager.processEvent(SimulationManager.java:156)
	at org.cloudbus.cloudsim.core.CloudSimEntity.run(CloudSimEntity.java:344)
	at org.cloudbus.cloudsim.core.CloudSim.executeRunnableEntities(CloudSim.java:575)
	at org.cloudbus.cloudsim.core.CloudSim.runClockTickAndProcessFutureEvents(CloudSim.java:498)
	at org.cloudbus.cloudsim.core.CloudSim.processEvents(CloudSim.java:299)
	at org.cloudbus.cloudsim.core.CloudSim.start(CloudSim.java:258)
	at com.pureedgesim.simulationcore.SimulationManager.startSimulation(SimulationManager.java:66)
	at com.pureedgesim.simulationcore.SimulationThread.startSimulation(SimulationThread.java:97)
	at com.pureedgesim.simulationcore.Simulation.launchSimulation(Simulation.java:79)
	at com.pureedgesim.MainApplication.main(MainApplication.java:10)

**Comment by thinkOver87** [comment]
I solved it,  we have to change the class name from DefaultOrchestrator to CustomEdgeOrchestrator in the simulationAbstract Class.   it looks like this

	protected  Class<? extends Orchestrator> orchestrator = CustomEdgeOrchestrator.class;
